version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 rm s3://$BUCKET --recursive
      - aws s3 cp dist/ s3://$BUCKET --recursive
artifacts:
    files:
      - 'dist/**/*'